#161290954 setup redux
andela/valinor-ah-frontend pull request #11
Opened 2018-11-30 20:49 UTC by augustineezinwa

#### What does this PR do?
- This PR setups the redux aspect of the application.
- Components were also connected to store and tested
#### Description of Task to be completed?
- Install redux
- Install react-redux
- Configure redux-dev-tools
- Configure store
- Connect components to store
- Render dummy component
- Write tests
#### How should this be manually tested?
- `npm test`
#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
-[ #161290954](https://www.pivotaltracker.com/story/show/161290954)
#### Screenshots (if appropriate)

#### Questions:
- N/A

2018-11-30 22:14 UTC, darthrighteous reviewed
There are a number of hound violations, fix those. Also, this is raised against master, fix that to develop.

2018-12-01 05:42 UTC, sulenchy commented
@Darthrighteous feedback duly noted.

2018-12-01 06:15 UTC, sulenchy commented
@Darthrighteous feedback implemented. No violation now

2018-12-03 14:16 UTC, tersoo-atsen approved these changes

2018-12-04 08:43 UTC, mbilesanmi requested changes
Please fix the 2 issues and it looks good for me. Then rebase @augustineezinwa

2018-12-04 08:43 UTC, mbilesanmi commented on src/App.js
> +  <div className='jumbotron'>
Your indentation seems to be way off in this file.

2018-12-04 08:43 UTC, mbilesanmi commented on src/reducers/buttonReducer.js
> +  const { ON_BUTTON, OFF_BUTTON } = types;
Move this to the import and import only the required types.

2018-12-04 15:14 UTC, mbilesanmi approved these changes

2018-12-04 15:23 UTC, KvNGCzA approved these changes

2018-12-04 16:30 UTC, mbilesanmi commented
1. Why do we still have conflicts?
2. How do we have up to 40 files changed?
3. Why are we having `*.snap` files showing up?
4. Are we squashing commits, or how is it that there is only 1 commit despite the magnitude of file changes we have?

@augustineezinwa @sulenchy

2018-12-04 16:48 UTC, sulenchy commented
> 1. Why do we still have conflicts?
> 2. How do we have up to 40 files changed?
> 3. Why are we having `*.snap` files showing up?
> 4. Are we squashing commits, or how is it that there is only 1 commit despite the magnitude of file changes we have?
> 
> @augustineezinwa @sulenchy
1. The conflict has been resolved now
2. We are not having the `*.snap` files again
3. we used `git commit --amend`

2018-12-04 16:54 UTC, augustineezinwa commented
> 1. Why do we still have conflicts?
> 2. How do we have up to 40 files changed?
> 3. Why are we having `*.snap` files showing up?
> 4. Are we squashing commits, or how is it that there is only 1 commit despite the magnitude of file changes we have?
> 
> @augustineezinwa @sulenchy

Everything is fine now

2018-12-04 16:55 UTC, augustineezinwa commented
> 1. Why do we still have conflicts?
> 2. How do we have up to 40 files changed?
> 3. Why are we having `*.snap` files showing up?
> 4. Are we squashing commits, or how is it that there is only 1 commit despite the magnitude of file changes we have?
> 


@mbilesanmi Everything is fine now

2018-12-04 16:56 UTC, merged