feat(view-sign-up-static-page): create static signup page
andela/valinor-ah-frontend pull request #15
Opened 2018-12-05 13:29 UTC by sulenchy

### What is it this PR doing
Create static signup page
#### Description of Task to be completed?
- create the small screen view
- create the big screen view
- add styles
- write snapshot tests for the component

#### How should this be manually tested?
- [Review App](https://valinor-ah-frontend-stag-pr-15.herokuapp.com/signup)

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#162380294](https://www.pivotaltracker.com/story/show/162380294)

#### Screenshots (if appropriate)
<img width="1431" alt="screen shot 2018-12-05 at 2 26 53 pm" src="https://user-images.githubusercontent.com/25647480/49516457-ec1fec80-f899-11e8-8ffd-fd509bb220bf.png">
<img width="564" alt="screen shot 2018-12-05 at 2 27 10 pm" src="https://user-images.githubusercontent.com/25647480/49516458-ec1fec80-f899-11e8-934e-fd71314d4a97.png">

#### Questions:
N/A

#### Link to review App
[Review App](https://valinor-ah-frontend-stag-pr-15.herokuapp.com/signup)

2018-12-06 10:31 UTC, augustineezinwa commented
@sulenchy Your markup for the desktop view seems not to be centralized. I suggest you add more paddings or margin beneath to get the markup centralized. Refer to the desktop figma mockup for more details.
Also for the signup on the mobile view. Your signup button is to be touching the bottom of a  phone screen. Consider adding padding to that button.

2018-12-06 10:38 UTC, KvNGCzA requested changes

2018-12-06 10:38 UTC, KvNGCzA commented on public/assets/styles/index.scss
> +$color-bg-light-blue:#007fff;
all variables should be in a variables.scss file

2018-12-06 10:38 UTC, KvNGCzA commented on public/assets/styles/signup.scss
> +$nav-red: #ff0000;
all variables should be in a variables.scss file

2018-12-06 10:38 UTC, KvNGCzA commented on public/assets/styles/signup.scss
> +    @mixin btn-rounded-basic(){
all mixins should be in a mixins.scss file

2018-12-08 07:23 UTC, tersoo-atsen approved these changes

2018-12-08 09:07 UTC, KvNGCzA reviewed
Please make all `px` em.

2018-12-08 09:07 UTC, KvNGCzA commented on public/assets/styles/index.scss
> +}
Line 8 to line 38 are not needed anymore. They are already declared below.

2018-12-08 09:07 UTC, KvNGCzA commented on public/assets/styles/mixins.scss
> +    border-radius: 30px;
I think this should be `em` like line 8 below

2018-12-08 09:07 UTC, KvNGCzA commented on public/assets/styles/mixins.scss
> +@mixin outerBoxShadow($v,$w, $x, $y, $z){
we have renamed this mixin outer-box-shadow. Please do the same.

2018-12-08 09:07 UTC, KvNGCzA commented on public/assets/styles/mixins.scss
> +    -ms-box-shadow: $v $w $x $y $z;
please remove this line. We wont need it.

2018-12-08 09:07 UTC, KvNGCzA commented on public/assets/styles/signup.scss
> +    $line-color: #ced4da;
This variable is out of place. It should be in the variables.scss file

2018-12-08 09:07 UTC, KvNGCzA commented on public/assets/styles/signup.scss
> +    .main-container .site-content {
all styles that are going to affect general div's that everyone will have should be in the index.scss file so we dont have to search through all scss files if something goes wrong.

2018-12-08 09:07 UTC, KvNGCzA commented on public/assets/styles/signup.scss
> +      &::placeholder {
use this mixin for placeholders
```
 @mixin placeholder($color){
  &::-webkit-input-placeholder{
    color: $color;
  }
  &::-moz-placeholder{
    color: $color;
  }
  &:-ms-input-placeholder{
    color: $color;
  }
  &:-moz-placeholder{
    color: $color;
  }
  &::placeholder{
    color: $color;
  }
}
```

2018-12-08 09:07 UTC, KvNGCzA commented on public/assets/styles/index.scss
> +@import '../../../public/assets/styles/signup';
this path should be `./signup`. please take out the scss extension on lines 4 and 5.

2018-12-08 11:03 UTC, KvNGCzA approved these changes

2018-12-08 15:33 UTC, augustineezinwa approved these changes
LGTM

2018-12-08 21:03 UTC, mbilesanmi commented on src/components/signup/SignUpPage.js
> +                    <h1 id="welcome">Welcome to Author's Haven!</h1>
```suggestion
                    <h1 id="welcome">Welcome to Author&quot;s Haven!</h1>
```

2018-12-08 21:07 UTC, mbilesanmi requested changes

2018-12-08 21:07 UTC, mbilesanmi commented on src/components/signup/SignUpPage.js
> +                      <input type="email" className="form-control email-input transparent" placeholder="FULL NAME" aria-label="Username" aria-describedby="basic-addon1" />
Why is this `type="email"`?

2018-12-08 21:29 UTC, sulenchy commented on src/components/signup/SignUpPage.js
> +                    <h1 id="welcome">Welcome to Author's Haven!</h1>
Feedback duly noted and implemented

2018-12-08 21:29 UTC, sulenchy commented on src/components/signup/SignUpPage.js
> +                      <input type="email" className="form-control email-input transparent" placeholder="FULL NAME" aria-label="Username" aria-describedby="basic-addon1" />
Feedback duly noted and implemented

2018-12-08 23:05 UTC, mbilesanmi approved these changes

2018-12-08 23:10 UTC, merged