#162380199 build landing Page
andela/valinor-ah-frontend pull request #17
Opened 2018-12-05 20:43 UTC by KvNGCzA

#### What does this PR do?
Build landing page

#### Description of Task to be completed?
- build landing page
- consume fake data
- style components
- write tests

#### How should this be manually tested?
- `npm run dev`
-  visit the landing page

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
[#162380199](https://www.pivotaltracker.com/story/show/162380199)

#### Screenshots (if appropriate)
<img width="1437" alt="screen shot 2018-12-05 at 9 34 13 pm" src="https://user-images.githubusercontent.com/30160407/49542689-9158b600-f8d6-11e8-9b91-83f8b66bffdc.png">
<img width="385" alt="screen shot 2018-12-05 at 9 35 50 pm" src="https://user-images.githubusercontent.com/30160407/49542707-99185a80-f8d6-11e8-9f05-d1c68e3b822d.png">

#### Questions:
N/A

#### Link to review app:

2018-12-06 12:30 UTC, augustineezinwa requested changes
Is there any reason why you disabled hound on using the scss-lint configuration? Address this.

2018-12-07 06:19 UTC, augustineezinwa approved these changes

2018-12-08 05:36 UTC, sulenchy approved these changes
LGTM

2018-12-08 08:24 UTC, tersoo-atsen approved these changes

2018-12-08 20:45 UTC, merged